In [18]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
import pymysql

In [19]:
DB_USER = "root"
DB_PASSWORD = 1234
DB_HOST = "localhost"
DB_PORT = "3306"
DB_NAME = "olist_db"

engine = create_engine(
    f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

In [20]:
funnel_base = pd.read_sql(
    "SELECT * FROM funnel_base",
    engine
)

In [21]:
funnel_base

,mql_id,first_contact_date,landing_page_id,origin,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue,is_converted,lead_month,conversion_month
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2018-02,NaT
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2017-10,NaT
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2018-03,NaT
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2018-01,NaT
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,None,reseller,NaN,0.0,1,2018-02,2018-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,feaba3ffcd2ff97501696c7f9a42f41c,2018-05-22,e42a14209c69c3e9cc6b042620465f12,paid_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2018-05,NaT
7996,a79cb53cd009ab92e0143b92baa2407b,2018-03-27,c494978688ccf66ad9fad3d6a3338c22,paid_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2018-03,NaT
7997,68f049a23ab109c6a0f6989bb9a02994,2017-08-27,b48ec5f3b04e9068441002a19df93c6c,organic_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2017-08,NaT
7998,4f8c96e2509b984329044c6682c88ee9,2017-10-06,a56671a54260a44923d32c2f08fad39c,organic_search,None,None,None,NaT,Unknown,Unknown,Unknown,NaN,NaN,None,Unknown,NaN,NaN,0,2017-10,NaT
7999,8a6492305a5fbcdcdd1a7f5a90764c07,2018-01-11,b76ef37428e6799c421989521c0e5077,direct_traffic,1bba9c94eb5c4e82fba9f7286fe81025,56bf83c4bb35763a51c2baab501b4c67,de63de0d10a6012430098db33c679b0b,2018-05-02 13:31:32,household_utilities,industry,eagle,NaN,NaN,None,manufacturer,NaN,0.0,1,2018-01,2018-05

In [22]:
pd.read_sql(
    "SHOW FULL TABLES WHERE Table_type = 'VIEW'",
    engine
)

   Tables_in_olist_db Table_type
0      vw_churn_proxy       VIEW
1  vw_conversion_rate       VIEW
2   vw_funnel_summary       VIEW
3   vw_monthly_cohort       VIEW